query($limit: Int, $page: Int, $search: String) {
  deliveries(limit: $limit, page: $page, search: $search) {
    data {
      purchaseOrderNumber
      quantity
      amount
      date
      transactionCount
      supplier {
        id
        name
      }
    }
    pagination {
      limit
      count
      pages
      page
    }
    errors {
      message
      type
      path
      value
    }
  }
}
