query SuppliersQuery($limit: Int, $page: Int, $search: String) {
  suppliers(limit: $limit, page: $page, search: $search) {
    data {
      id
      code
      name
      tinNumber
    }
    pagination {
      limit
      count
      pages
      page
    }
    errors {
      message
      type
      path
      value
    }
  }
}