query SuppliersQuery($limit: Int, $page: Int) {
  suppliers(limit: $limit, page: $page) {
    data {
      id
      code
      name
      TIN
      email
      representative
    }
    pagination {
      limit
      count
      pages
      page
    }
    errors {
      message
      type
      path
      value
    }
  }
}